<?php

namespace Screwfix;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-07-11 at 19:06:26.
 */
class BankHolidayFilterTest extends \UnitTestCase {

	/**
	 * @var BankHolidayFilter
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new BankHolidayFilter(array(
			'2012-05-05' => 'Bank Holiday 1', 
			'2012-09-04' => 'Bank holiday 2'
		));
	}

	/**
	 * @covers Screwfix\BankHolidayFilter::day
	 */
	public function testDayBankHolidayFound()
	{
		$this->assertEquals('Bank Holiday 1', $this->object->day('2012-05-05'));
	}

	/**
	 * @covers Screwfix\BankHolidayFilter::day
	 */
	public function testDayBankHolidayNotFound()
	{
		$this->assertEquals(null, $this->object->day('2012-05-08'));
	}

}
