<?php

namespace Screwfix;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-07-10 at 20:06:48.
 */
class CalendarDataTest extends \UnitTestCase {

	/**
	 * @var CalendarData
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new CalendarData;
		$this->_days = array(
			1970 =>
			array(
				2 =>
				array(// CalendarMonthPeriod('1970/02/01', 1)
					0 => 2156400,
					1 => 2242800,
					2 => 2329200,
					3 => 2415600,
					4 => 2502000,
					5 => 2588400,
					6 => 2674800,
					7 => 2761200,
					8 => 2847600,
					9 => 2934000,
					10 => 3020400,
					11 => 3106800,
					12 => 3193200,
					13 => 3279600,
					14 => 3366000,
					15 => 3452400,
					16 => 3538800,
					17 => 3625200,
					18 => 3711600,
					19 => 3798000,
					20 => 3884400,
					21 => 3970800,
					22 => 4057200,
					23 => 4143600,
					24 => 4230000,
					25 => 4316400,
					26 => 4402800,
					27 => 4489200,
					28 => 4575600,
					29 => 4662000,
					30 => 4748400,
					31 => 4834800,
					32 => 4921200,
					33 => 5007600,
					34 => 5094000,
				),
			),
		);
	}

	/**
	 * @covers Screwfix\CalendarData::addFilter
	 * @todo   Implement testAddFilter().
	 */
	public function testAddFilter()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet. I don\'t know how'
		);
	}

	/**
	 * @covers Screwfix\CalendarData::build
	 * @todo   Implement testBuild().
	 */
	public function testBuild()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet. I don\'t know how'
		);
		
		
	}

}
