<?php

namespace Screwfix;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-07-11 at 19:06:26.
 */
class HolidayFilterTest extends \UnitTestCase {

	/**
	 * @var BankHolidayFilter
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new HolidayFilter(array(
			'2012-05-05' => 0, // all day
			'2012-05-06' => 1, // halfday
		));
	}

	/**
	 * @covers Screwfix\BankHolidayFilter::day
	 */
	public function testDayHolidayFound()
	{
		$this->assertEquals(0, $this->object->day('2012-05-05'));
	}

	/**
	 * @covers Screwfix\BankHolidayFilter::day
	 */
	public function testDayHolidayNotFound()
	{
		$this->assertEquals(null, $this->object->day('2012-09-08'));
	}

}
